# Hydra explorer instance with it's chain observers as it is deployed to
# explorer.hydra.family
networks:
  hydra-explorer:
    driver: bridge

services:
  hydra-explorer:
    image: ghcr.io/cardano-scaling/hydra-explorer:unstable
    ports:
      - "80:8000"
    command:
      [ "--client-port", "8000"
      , "--observer-port", "8001" # not bound to host
      ]
    networks:
      - hydra-explorer
    restart: always

  # List of hydra-chain-observers

  ## 0.20

  hydra-chain-observer-preview-0.20:
    # TODO: cut release 0.20.1
    image: ghcr.io/cardano-scaling/hydra-chain-observer@sha256:d6f6d511465696715e08fba7bda7c440761c59ee2b0eac124057f7b207c7069c
    volumes:
      - "/data/cardano/preview:/data"
    command:
      [ "--node-socket", "/data/node.socket"
      , "--testnet-magic", "2"
      # NOTE: Block in which 0.20.0 scripts were published
      , "--start-chain-from", "71938562.2c5fc734343ad1bf8ce2df999421cca15dffdd2b8e1909dad7127b9eaacf8b9c"
      # NOTE: Reachable via hydra-explorer network
      , "--explorer", "http://hydra-explorer:8001"
      ]
    networks:
      - hydra-explorer
    restart: always

  hydra-chain-observer-preprod-0.20:
    # TODO: cut release 0.20.1
    image: ghcr.io/cardano-scaling/hydra-chain-observer@sha256:d6f6d511465696715e08fba7bda7c440761c59ee2b0eac124057f7b207c7069c
    volumes:
      - "/data/cardano/preprod:/data"
    command:
      [ "--node-socket", "/data/node.socket"
      , "--testnet-magic", "1"
      # NOTE: Block in which 0.20.0 scripts were published
      , "--start-chain-from", "82913877.aa62d900ecbd6a073e1b5bb8c014413365c26a3675bd81dc567013340bf94ec3"
      # NOTE: Reachable via hydra-explorer network
      , "--explorer", "http://hydra-explorer:8001"
      ]
    networks:
      - hydra-explorer
    restart: always

  hydra-chain-observer-mainnet-0.20:
    # TODO: cut release 0.20.1
    image: ghcr.io/cardano-scaling/hydra-chain-observer@sha256:d6f6d511465696715e08fba7bda7c440761c59ee2b0eac124057f7b207c7069c
    volumes:
      - "/data/cardano/mainnet:/data"
    command:
      [ "--node-socket", "/data/node.socket"
      , "--mainnet"
      # NOTE: Block in which 0.20.0 scripts were published
      , "--start-chain-from", "147018612.3e8c336100a055858f83c1853908bc73aacee5c68e3bf3f9729361a85d815e02"
      # NOTE: Reachable via hydra-explorer network
      , "--explorer", "http://hydra-explorer:8001"
      ]
    networks:
      - hydra-explorer
    restart: always

  ## 0.19

  hydra-chain-observer-preview-0.19:
    # TODO: cut release 0.19.1
    image: ghcr.io/cardano-scaling/hydra-chain-observer@sha256:d28b74adfa8714985f730a8396c64de95c69aab45d9b7e251b8efd906693ce34
    volumes:
      - "/data/cardano/preview:/data"
    command:
      [ "--node-socket", "/data/node.socket"
      , "--testnet-magic", "2"
      # NOTE: Block in which 0.19.0 scripts were published
      , "--start-chain-from", "59574002.1ba4ee1f87e8ebbf4682662839592639591133d589a8a84246bbb3c7ce2b713b"
      # NOTE: Reachable via hydra-explorer network
      , "--explorer", "http://hydra-explorer:8001"
      ]
    networks:
      - hydra-explorer
    restart: always

  hydra-chain-observer-preprod-0.19:
    # TODO: cut release 0.19.1
    image: ghcr.io/cardano-scaling/hydra-chain-observer@sha256:d28b74adfa8714985f730a8396c64de95c69aab45d9b7e251b8efd906693ce34
    volumes:
      - "/data/cardano/preprod:/data"
    command:
      [ "--node-socket", "/data/node.socket"
      , "--testnet-magic", "1"
      # NOTE: Block in which 0.19.0 scripts were published
      , "--start-chain-from", "70548651.ea1aa2ff826790a579a0d82ce7eee9ed943cf81e508084cea69539cb2018cbb6"
      # NOTE: Reachable via hydra-explorer network
      , "--explorer", "http://hydra-explorer:8001"
      ]
    networks:
      - hydra-explorer
    restart: always

  hydra-chain-observer-mainnet-0.19:
    # TODO: cut release 0.19.1
    image: ghcr.io/cardano-scaling/hydra-chain-observer@sha256:d28b74adfa8714985f730a8396c64de95c69aab45d9b7e251b8efd906693ce34
    volumes:
      - "/data/cardano/mainnet:/data"
    command:
      [ "--node-socket", "/data/node.socket"
      , "--mainnet"
      # NOTE: Block in which 0.19.0 scripts were published
      , "--start-chain-from", "134668621.ea6a3c1b707b3159a0f580af2c63cb1173c44e8b97ee402bd0c4a0cf67f51975"
      # NOTE: Reachable via hydra-explorer network
      , "--explorer", "http://hydra-explorer:8001"
      ]
    networks:
      - hydra-explorer
    restart: always

  # One cardano node per network

  cardano-node-preview:
    image: ghcr.io/intersectmbo/cardano-node:10.1.4
    volumes:
      - /data/cardano/preview:/data
    environment:
      - CARDANO_CONFIG=/data/config.json
      - CARDANO_TOPOLOGY=/data/topology.json
      - CARDANO_DATABASE_PATH=/data/db
      - CARDANO_SOCKET_PATH=/data/node.socket # used by cardano-node
      - CARDANO_NODE_SOCKET_PATH=/data/node.socket # used by cardano-cli
      - CARDANO_LOG_DIR=/data/logs
    command:
      [ "run" ]
    restart: always

  cardano-node-preprod:
    image: ghcr.io/intersectmbo/cardano-node:10.1.4
    volumes:
      - /data/cardano/preprod:/data
    environment:
      - CARDANO_CONFIG=/data/config.json
      - CARDANO_TOPOLOGY=/data/topology.json
      - CARDANO_DATABASE_PATH=/data/db
      - CARDANO_SOCKET_PATH=/data/node.socket # used by cardano-node
      - CARDANO_NODE_SOCKET_PATH=/data/node.socket # used by cardano-cli
      - CARDANO_LOG_DIR=/data/logs
    command:
      [ "run" ]
    restart: always

  cardano-node-mainnet:
    image: ghcr.io/intersectmbo/cardano-node:10.1.4
    volumes:
      - /data/cardano/mainnet:/data
    environment:
      - CARDANO_CONFIG=/data/config.json
      - CARDANO_TOPOLOGY=/data/topology.json
      - CARDANO_DATABASE_PATH=/data/db
      - CARDANO_SOCKET_PATH=/data/node.socket # used by cardano-node
      - CARDANO_NODE_SOCKET_PATH=/data/node.socket # used by cardano-cli
      - CARDANO_LOG_DIR=/data/logs
    command:
      [ "run" ]
    restart: always
