# Hydra explorer instance with it's chain observers as it is deployed to
# explorer.hydra.family
networks:
  hydra-explorer:
    driver: bridge

services:
  hydra-explorer:
    image: ghcr.io/cardano-scaling/hydra-explorer:unstable
    ports:
      - "8080:8000"
    command:
      [ "--client-port", "8000"
      , "--observer-port", "8001" # not bound to host
      ]
    environment:
      # Hide debug output.
      - LOG_LEVEL=info
    networks:
      - hydra-explorer
    restart: always
    logging:
      driver: journald

  # List of hydra-chain-observers

  ## 1.0.0

  hydra-chain-observer-preview-1.0.0:
    image: ghcr.io/cardano-scaling/hydra-chain-observer:1.0.0
    volumes:
      - "/data/cardano/preview:/data"
    command:
      [ "--node-socket", "/data/node.socket"
      , "--testnet-magic", "2"
      # NOTE: Block in which 1.0.0 scripts were published
      , "--start-chain-from", "93287427.ab165d330848472a4afaf03ae611dc5aeebc7af02481f28c7c2d6059b33ea070"
      , "--explorer", "http://hydra-explorer:8001"
      ]
    depends_on:
      hydra-explorer:
        condition: service_started
        restart: true
    networks:
      - hydra-explorer
    restart: always
    logging:
      driver: journald

  hydra-chain-observer-preprod-1.0.0:
    image: ghcr.io/cardano-scaling/hydra-chain-observer:1.0.0
    volumes:
      - "/data/cardano/preprod:/data"
    command:
      [ "--node-socket", "/data/node.socket"
      , "--testnet-magic", "1"
      # NOTE: Block in which 1.0.0 scripts were published
      , "--start-chain-from", "104261385.53bd33ef5f8b6b29f2223926ed08de3334f0bbfc5f92b49ec197b09a0221f88d"
      , "--explorer", "http://hydra-explorer:8001"
      ]
    depends_on:
      hydra-explorer:
        condition: service_started
        restart: true
    networks:
      - hydra-explorer
    restart: always
    logging:
      driver: journald

  hydra-chain-observer-mainnet-1.0.0:
    image: ghcr.io/cardano-scaling/hydra-chain-observer:1.0.0
    volumes:
      - "/data/cardano/mainnet:/data"
    command:
      [ "--node-socket", "/data/node.socket"
      , "--mainnet"
      # NOTE: Block in which 1.0.0 scripts were published
      , "--start-chain-from", "168379683.acbe55d4758c8f141a03daf589477670f0b7103d5a46b32c145a4a676ceb4fd9"
      , "--explorer", "http://hydra-explorer:8001"
      ]
    depends_on:
      hydra-explorer:
        condition: service_started
        restart: true
    networks:
      - hydra-explorer
    restart: always
    logging:
      driver: journald

  ## 0.22.4

  hydra-chain-observer-preview-0.22.4:
    image: ghcr.io/cardano-scaling/hydra-chain-observer:0.22.4
    volumes:
      - "/data/cardano/preview:/data"
    command:
      [ "--node-socket", "/data/node.socket"
      , "--testnet-magic", "2"
      # NOTE: Block in which 0.22.0 scripts were published
      , "--start-chain-from", "83494816.03d86af365c9ff1638aeacb891343c26a3c50066b6319b5c5ac0ed77d633a9c6"
      # NOTE: Reachable via hydra-explorer network
      , "--explorer", "http://hydra-explorer:8001"
      ]
    depends_on:
      hydra-explorer:
        condition: service_started
        restart: true
    networks:
      - hydra-explorer
    restart: always
    logging:
      driver: journald

  hydra-chain-observer-preprod-0.22.4:
    image: ghcr.io/cardano-scaling/hydra-chain-observer:0.22.4
    volumes:
      - "/data/cardano/preprod:/data"
    command:
      [ "--node-socket", "/data/node.socket"
      , "--testnet-magic", "1"
      # NOTE: Block in which 0.22.0 scripts were published
      , "--start-chain-from", "94474101.da5a870f317943ea8e92b070875b9fb806659b6df3a2871a6addf8f9b8fdd2ea"
      # NOTE: Reachable via hydra-explorer network
      , "--explorer", "http://hydra-explorer:8001"
      ]
    depends_on:
      hydra-explorer:
        condition: service_started
        restart: true
    networks:
      - hydra-explorer
    restart: always
    logging:
      driver: journald

  hydra-chain-observer-mainnet-0.22.4:
    image: ghcr.io/cardano-scaling/hydra-chain-observer:0.22.4
    volumes:
      - "/data/cardano/mainnet:/data"
    command:
      [ "--node-socket", "/data/node.socket"
      , "--mainnet"
      # NOTE: Block in which 0.22.0 scripts were published
      , "--start-chain-from", "158590430.97a33745faba570583613f5bf994ff7fbe0933933ac2ad0e635173102a84a962"
      # NOTE: Reachable via hydra-explorer network
      , "--explorer", "http://hydra-explorer:8001"
      ]
    depends_on:
      hydra-explorer:
        condition: service_started
        restart: true
    networks:
      - hydra-explorer
    restart: always
    logging:
      driver: journald

  ## 0.22

  hydra-chain-observer-preview-0.22:
    image: ghcr.io/cardano-scaling/hydra-chain-observer:0.22.0
    volumes:
      - "/data/cardano/preview:/data"
    command:
      [ "--node-socket", "/data/node.socket"
      , "--testnet-magic", "2"
      # NOTE: Block in which 0.22.0 scripts were published
      , "--start-chain-from", "83494816.03d86af365c9ff1638aeacb891343c26a3c50066b6319b5c5ac0ed77d633a9c6"
      # NOTE: Reachable via hydra-explorer network
      , "--explorer", "http://hydra-explorer:8001"
      ]
    depends_on:
      hydra-explorer:
        condition: service_started
        restart: true
    networks:
      - hydra-explorer
    restart: always
    logging:
      driver: journald

  hydra-chain-observer-preprod-0.22:
    image: ghcr.io/cardano-scaling/hydra-chain-observer:0.22.0
    volumes:
      - "/data/cardano/preprod:/data"
    command:
      [ "--node-socket", "/data/node.socket"
      , "--testnet-magic", "1"
      # NOTE: Block in which 0.22.0 scripts were published
      , "--start-chain-from", "94474101.da5a870f317943ea8e92b070875b9fb806659b6df3a2871a6addf8f9b8fdd2ea"
      # NOTE: Reachable via hydra-explorer network
      , "--explorer", "http://hydra-explorer:8001"
      ]
    depends_on:
      hydra-explorer:
        condition: service_started
        restart: true
    networks:
      - hydra-explorer
    restart: always
    logging:
      driver: journald

  hydra-chain-observer-mainnet-0.22:
    image: ghcr.io/cardano-scaling/hydra-chain-observer:0.22.0
    volumes:
      - "/data/cardano/mainnet:/data"
    command:
      [ "--node-socket", "/data/node.socket"
      , "--mainnet"
      # NOTE: Block in which 0.22.0 scripts were published
      , "--start-chain-from", "158590430.97a33745faba570583613f5bf994ff7fbe0933933ac2ad0e635173102a84a962"
      # NOTE: Reachable via hydra-explorer network
      , "--explorer", "http://hydra-explorer:8001"
      ]
    depends_on:
      hydra-explorer:
        condition: service_started
        restart: true
    networks:
      - hydra-explorer
    restart: always
    logging:
      driver: journald

  ## 0.21

  hydra-chain-observer-preview-0.21:
    image: ghcr.io/cardano-scaling/hydra-chain-observer:0.21.0
    volumes:
      - "/data/cardano/preview:/data"
    command:
      [ "--node-socket", "/data/node.socket"
      , "--testnet-magic", "2"
      # NOTE: Block in which 0.21.0 scripts were published
      , "--start-chain-from", "79181007.89c0e835770246ced1eaf8f4477a2600073ad0ec1ceea62505d9665528a00b13"
      # NOTE: Reachable via hydra-explorer network
      , "--explorer", "http://hydra-explorer:8001"
      ]
    depends_on:
      hydra-explorer:
        condition: service_started
        restart: true
    networks:
      - hydra-explorer
    restart: always
    logging:
      driver: journald

  hydra-chain-observer-preprod-0.21:
    image: ghcr.io/cardano-scaling/hydra-chain-observer:0.21.0
    volumes:
      - "/data/cardano/preprod:/data"
    command:
      [ "--node-socket", "/data/node.socket"
      , "--testnet-magic", "1"
      # NOTE: Block in which 0.21.0 scripts were published
      , "--start-chain-from", "90154257.95d0da1ddd4ba70b2b29f364beae7d2cb35365fdf8df8c5e19a27b52dd8f0f10"
      # NOTE: Reachable via hydra-explorer network
      , "--explorer", "http://hydra-explorer:8001"
      ]
    depends_on:
      hydra-explorer:
        condition: service_started
        restart: true
    networks:
      - hydra-explorer
    restart: always
    logging:
      driver: journald

  hydra-chain-observer-mainnet-0.21:
    image: ghcr.io/cardano-scaling/hydra-chain-observer:0.21.0
    volumes:
      - "/data/cardano/mainnet:/data"
    command:
      [ "--node-socket", "/data/node.socket"
      , "--mainnet"
      # NOTE: Block in which 0.21.0 scripts were published
      , "--start-chain-from", "154271531.7368a0e9b54943547b40f989d920fba4a0a347475e90ea0118924ecb4e357d3d"
      # NOTE: Reachable via hydra-explorer network
      , "--explorer", "http://hydra-explorer:8001"
      ]
    depends_on:
      hydra-explorer:
        condition: service_started
        restart: true
    networks:
      - hydra-explorer
    restart: always
    logging:
      driver: journald

  ## 0.20

  hydra-chain-observer-preview-0.20:
    image: ghcr.io/cardano-scaling/hydra-chain-observer:0.20.1
    volumes:
      - "/data/cardano/preview:/data"
    command:
      [ "--node-socket", "/data/node.socket"
      , "--testnet-magic", "2"
      # NOTE: Block in which 0.20.0 scripts were published
      , "--start-chain-from", "71938562.2c5fc734343ad1bf8ce2df999421cca15dffdd2b8e1909dad7127b9eaacf8b9c"
      # NOTE: Reachable via hydra-explorer network
      , "--explorer", "http://hydra-explorer:8001"
      ]
    depends_on:
      hydra-explorer:
        condition: service_started
        restart: true
    networks:
      - hydra-explorer
    restart: always
    logging:
      driver: journald

  hydra-chain-observer-preprod-0.20:
    image: ghcr.io/cardano-scaling/hydra-chain-observer:0.20.1
    volumes:
      - "/data/cardano/preprod:/data"
    command:
      [ "--node-socket", "/data/node.socket"
      , "--testnet-magic", "1"
      # NOTE: Block in which 0.20.0 scripts were published
      , "--start-chain-from", "82913877.aa62d900ecbd6a073e1b5bb8c014413365c26a3675bd81dc567013340bf94ec3"
      # NOTE: Reachable via hydra-explorer network
      , "--explorer", "http://hydra-explorer:8001"
      ]
    depends_on:
      hydra-explorer:
        condition: service_started
        restart: true
    networks:
      - hydra-explorer
    restart: always
    logging:
      driver: journald

  hydra-chain-observer-mainnet-0.20:
    image: ghcr.io/cardano-scaling/hydra-chain-observer:0.20.1
    volumes:
      - "/data/cardano/mainnet:/data"
    command:
      [ "--node-socket", "/data/node.socket"
      , "--mainnet"
      # NOTE: Block in which 0.20.0 scripts were published
      , "--start-chain-from", "147018612.3e8c336100a055858f83c1853908bc73aacee5c68e3bf3f9729361a85d815e02"
      # NOTE: Reachable via hydra-explorer network
      , "--explorer", "http://hydra-explorer:8001"
      ]
    depends_on:
      hydra-explorer:
        condition: service_started
        restart: true
    networks:
      - hydra-explorer
    restart: always
    logging:
      driver: journald

  ## 0.19

  hydra-chain-observer-preview-0.19:
    image: ghcr.io/cardano-scaling/hydra-chain-observer:0.19.1
    volumes:
      - "/data/cardano/preview:/data"
    command:
      [ "--node-socket", "/data/node.socket"
      , "--testnet-magic", "2"
      # NOTE: Block in which 0.19.0 scripts were published
      , "--start-chain-from", "59574002.1ba4ee1f87e8ebbf4682662839592639591133d589a8a84246bbb3c7ce2b713b"
      # NOTE: Reachable via hydra-explorer network
      , "--explorer", "http://hydra-explorer:8001"
      ]
    depends_on:
      hydra-explorer:
        condition: service_started
        restart: true
    networks:
      - hydra-explorer
    restart: always
    logging:
      driver: journald

  hydra-chain-observer-preprod-0.19:
    image: ghcr.io/cardano-scaling/hydra-chain-observer:0.19.1
    volumes:
      - "/data/cardano/preprod:/data"
    command:
      [ "--node-socket", "/data/node.socket"
      , "--testnet-magic", "1"
      # NOTE: Block in which 0.19.0 scripts were published
      , "--start-chain-from", "70548651.ea1aa2ff826790a579a0d82ce7eee9ed943cf81e508084cea69539cb2018cbb6"
      # NOTE: Reachable via hydra-explorer network
      , "--explorer", "http://hydra-explorer:8001"
      ]
    depends_on:
      hydra-explorer:
        condition: service_started
        restart: true
    networks:
      - hydra-explorer
    restart: always
    logging:
      driver: journald

  hydra-chain-observer-mainnet-0.19:
    image: ghcr.io/cardano-scaling/hydra-chain-observer:0.19.1
    volumes:
      - "/data/cardano/mainnet:/data"
    command:
      [ "--node-socket", "/data/node.socket"
      , "--mainnet"
      # NOTE: Block in which 0.19.0 scripts were published
      , "--start-chain-from", "134668621.ea6a3c1b707b3159a0f580af2c63cb1173c44e8b97ee402bd0c4a0cf67f51975"
      # NOTE: Reachable via hydra-explorer network
      , "--explorer", "http://hydra-explorer:8001"
      ]
    depends_on:
      hydra-explorer:
        condition: service_started
        restart: true
    networks:
      - hydra-explorer
    restart: always
    logging:
      driver: journald

  # One cardano node per network

  cardano-node-preview:
    image: ghcr.io/intersectmbo/cardano-node:10.1.4
    volumes:
      - /data/cardano/preview:/data
    environment:
      - CARDANO_CONFIG=/data/config.json
      - CARDANO_TOPOLOGY=/data/topology.json
      - CARDANO_DATABASE_PATH=/data/db
      - CARDANO_SOCKET_PATH=/data/node.socket # used by cardano-node
      - CARDANO_NODE_SOCKET_PATH=/data/node.socket # used by cardano-cli
      - CARDANO_LOG_DIR=/data/logs
    command:
      [ "run" ]
    restart: always
    logging:
      driver: journald

  cardano-node-preprod:
    image: ghcr.io/intersectmbo/cardano-node:10.1.4
    volumes:
      - /data/cardano/preprod:/data
    environment:
      - CARDANO_CONFIG=/data/config.json
      - CARDANO_TOPOLOGY=/data/topology.json
      - CARDANO_DATABASE_PATH=/data/db
      - CARDANO_SOCKET_PATH=/data/node.socket # used by cardano-node
      - CARDANO_NODE_SOCKET_PATH=/data/node.socket # used by cardano-cli
      - CARDANO_LOG_DIR=/data/logs
    command:
      [ "run" ]
    restart: always
    logging:
      driver: journald

  cardano-node-mainnet:
    image: ghcr.io/intersectmbo/cardano-node:10.1.4
    volumes:
      - /data/cardano/mainnet:/data
    environment:
      - CARDANO_CONFIG=/data/config.json
      - CARDANO_TOPOLOGY=/data/topology.json
      - CARDANO_DATABASE_PATH=/data/db
      - CARDANO_SOCKET_PATH=/data/node.socket # used by cardano-node
      - CARDANO_NODE_SOCKET_PATH=/data/node.socket # used by cardano-cli
      - CARDANO_LOG_DIR=/data/logs
    command:
      [ "run" ]
    restart: always
    logging:
      driver: journald
