name: "CI"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
on:
  merge_group:
  push:
    branches:
    - main
    - release
  pull_request:

permissions:
  checks: write
  pull-requests: write

jobs:
  build-test:
    name: "Build & test"
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v4

    - name: ❄ Prepare nix
      uses: cachix/install-nix-action@v30
      with:
        extra_nix_config: |
          accept-flake-config = true
          log-lines = 1000

    - name: ❄ Cachix cache of nix derivations
      uses: cachix/cachix-action@v15
      with:
        name: cardano-scaling
        authToken: '${{ secrets.CACHIX_CARDANO_SCALING_AUTH_TOKEN }}'

    - name: ❓ Build and test
      run: |
        # Build the web frontend; it is part of the docker image built on
        # main and would otherwise only break after merging.
        nix build .#hydra-explorer-web

        # XXX: All this is too slow.
        #
        # nix build .#docker
        # nix run .#apps.x86_64-linux."hydra-explorer:exe:hydra-explorer" -- --help

        # Note: The tests need to find `json-schemas/client-api.yaml`;
        # so they need to be run in this specific folder.
        cd hydra-explorer

        # We need the packages in the shell to run the tests
        nix develop -c cabal update
        nix develop -c cabal test all
